### PR TITLE
Updated Predictor

### PR DESCRIPTION
**Pull request by sparkie108**
Updated Predictor code. 
Predictor now returns weekly min, max values
Added licence

I can lo longer get the app to run in the simulators on my machine, so I haven't been able to integration test.

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
So the functionality should be the same I assume? 

For the license We could check it in as a file and I can include it in the app. I assume it is for your port of the original source code?

**Comment by sparkie108** [comment]
Yes the functionality is the same, but the predictions should be more accurate giving narrower ranges.

The licence only applies to Prediction.cs as that's the only file I converted from the Javascript, I'll leave you to decide how you want to include it.

**Comment by jamesmontemagno** [comment]
gotcha! sounds good! <3

**Comment by jamesmontemagno** [comment]
Looks like I should have tested first... just crashing app :( whoops

**Pull request merged**
